### ISSUE TITLE
Feedback on other Serverless setups

### ISSUE THREAD

**Issue by goncaloneves** [FidelLimited/serverless-plugin-optimize#2]
We are using this plugin in production but would be useful to get some information how does it handle other setups.

Cheers! 😃

**Comment by ro-savage** [comment]
We've been using it for a couple months as we ready for production launch. Only thing that caught us out was #32. Beyond that it was easy to setup and everything just worked.

**Comment by darbio** [comment]
I've just converted a project to use it (25 functions) and it's sped up deployment a lot. I've had some issues with using npm projects that don't play nicely with (I suspect) browserify (such as nodemailer) which I'm still working through.

Errors such as:

```
Unable to import module '_optimize/tsz-serverless-api-dev-wp-shared-email/functions/workers/shared/email/handler': Error
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at s (/var/task/_optimize/tsz-serverless-api-dev-wp-shared-email/functions/workers/shared/email/handler.js:1:554)
at /var/task/_optimize/tsz-serverless-api-dev-wp-shared-email/functions/workers/shared/email/handler.js:1:745
at Object.467.semver (/var/task/_optimize/tsz-serverless-api-dev-wp-shared-email/functions/workers/shared/email/handler.js:86189:18)
at s (/var/task/_optimize/tsz-serverless-api-dev-wp-shared-email/functions/workers/shared/email/handler.js:1:694)
at /var/task/_optimize/tsz-serverless-api-dev-wp-shared-email/functions/workers/shared/email/handler.js:1:745
at Object.1190.chalk (/var/task/_optimize/tsz-serverless-api-dev-wp-shared-email/functions/workers/shared/email/handler.js:235973:15)
at s (/var/task/_optimize/tsz-serverless-api-dev-wp-shared-email/functions/workers/shared/email/handler.js:1:694)
at /var/task/_optimize/tsz-serverless-api-dev-wp-shared-email/functions/workers/shared/email/handler.js:1:745
at Object.1188../css (/var/task/_optimize/tsz-serverless-api-dev-wp-shared-email/functions/workers/shared/email/handler.js:235686:14)
at s (/var/task/_optimize/tsz-serverless-api-dev-wp-shared-email/functions/workers/shared/email/handler.js:1:694)
at /var/task/_optimize/tsz-serverless-api-dev-wp-shared-email/functions/workers/shared/email/handler.js:1:745
at Object.1189../css (/var/task/_optimize/tsz-serverless-api-dev-wp-shared-email/functions/workers/shared/email/handler.js:235965:15)
```

Currently working through these to see what the issue is.

**Comment by bwisitero** [comment]
@darbio  did u get to resolve this issue?

**Comment by darbio** [comment]
@bwistero yes and no.. See #54 - I removed the offending packages and replaced them with ones that could be webpacked. We're using it in production now with no issues.
