### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by Bill-Niz** [FidelLimited/serverless-plugin-optimize#29]
When calling my lambda i have : 

`
    "errorMessage": "Cannot find module '/var/task/handler'",
    "errorType": "Error",
    "stackTrace": [
        "Function.Module._load (module.js:276:25)",
        "Module.require (module.js:353:17)",
        "require (internal/module.js:12:17)"
    ]
}
`

**Comment by goncaloneves** [comment]
The module is not found, so make sure your paths are correct and always use relative paths.

Besides that, you can disable minification, and go through stack trace debugging.

**Comment by Bill-Niz** [comment]
@goncaloneves 
I have learned nothing new with "minify false"

`Unable to import module 'handler': Error
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
`

I think lambda doesn't find my `handle.js`

When i download the deployment package of my lambda in AWS console, i get zip with files achitecture like `_optimiez/'my-labda-name/handler.js'`

When i don't optimize i get `my-labda-name/handler.js'`
with all files.

Why does the plugin add the `_optimize` directory?

**Comment by goncaloneves** [comment]
The prefix folder (_optimize) is where the plugin bundles the files together and then changes the handler path in the package object from SLS to zip and deploy the prefix instead. That's why you need relative paths inside your code. This is invisible to the user, so just follow SLS instructions and then follow the plugin instructions and you should be fine.

GL on that

**Comment by Bill-Niz** [comment]
Problem solved!

I had to make first a full deploy with `sls deploy`.

Instead of only  doing `sls deploy function -f fct-name`

Thx a lot.

**Comment by goncaloneves** [comment]
Cool 👌 Keep it up.

**Comment by darbio** [comment]
I'm still getting this issue:

```
Unable to import module '_optimize/tsz-serverless-api-dev-jwt-authorizer/functions/authorizers/jwt/handler': Error
at /var/task/_optimize/tsz-serverless-api-dev-jwt-authorizer/functions/authorizers/jwt/handler.js:1:745
at Function._load (/var/task/_optimize/tsz-serverless-api-dev-jwt-authorizer/functions/authorizers/jwt/handler.js:1899:18)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at s (/var/task/_optimize/tsz-serverless-api-dev-jwt-authorizer/functions/authorizers/jwt/handler.js:1:554)
at /var/task/_optimize/tsz-serverless-api-dev-jwt-authorizer/functions/authorizers/jwt/handler.js:1:745
at Object.instrument (/var/task/_optimize/tsz-serverless-api-dev-jwt-authorizer/functions/authorizers/jwt/handler.js:1909:5)
at Raven.install (/var/task/_optimize/tsz-serverless-api-dev-jwt-authorizer/functions/authorizers/jwt/handler.js:1370:18)
at installRaven (/var/task/_optimize/tsz-serverless-api-dev-jwt-authorizer/functions/authorizers/jwt/handler.js:2956:4)
at Function.handler (/var/task/_optimize/tsz-serverless-api-dev-jwt-authorizer/functions/authorizers/jwt/handler.js:3141:4)
at Object.1.../../../utils/logger (/var/task/_optimize/tsz-serverless-api-dev-jwt-authorizer/functions/authorizers/jwt/handler.js:2:1613)
at s (/var/task/_optimize/tsz-serverless-api-dev-jwt-authorizer/functions/authorizers/jwt/handler.js:1:694)
at e (/var/task/_optimize/tsz-serverless-api-dev-jwt-authorizer/functions/authorizers/jwt/handler.js:1:865)
at /var/task/_optimize/tsz-serverless-api-dev-jwt-authorizer/functions/authorizers/jwt/handler.js:1:894
at a (/var/task/_optimize/tsz-serverless-api-dev-jwt-authorizer/functions/authorizers/jwt/handler.js:1:150)
at Object.<anonymous> (/var/task/_optimize/tsz-serverless-api-dev-jwt-authorizer/functions/authorizers/jwt/handler.js:1:385)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
```

Any tips? I added the plugin to an existing serverless deployment.

**Comment by maazmk** [comment]
any update?
