### ISSUE TITLE
Error: Cannot find module './drivers/node-mongodb-native/connection' 

### ISSUE THREAD

**Issue by tbaustin** [FidelLimited/serverless-plugin-optimize#56]
When using mongoose , as in just doing something like `import mongoose from 'mongoose'` I get this error: `Error: Cannot find module './drivers/node-mongodb-native/connection'`. It gets fixed if I remove the plugin so I am pretty sure this is causing it.

**Comment by jamesAtcodeninja** [comment]
I'm having this problem with `knex` as well when it requires a relative file.

**Comment by rodrigoreis22** [comment]
Same problem here. My tree structure:

```
├── _optimize
│   ├── arena-node-api-dev-app
│   └── arena-node-api-dev-billing
├── app
│   ├── __mocks__
│   ├── apis
│   ├── config.js
│   ├── db_init.js
│   ├── external
│   ├── index.js
│   ├── node_modules
│   ├── package-lock.json
│   ├── package.json
│   ├── routes
│   ├── schemas
│   └── utils
├── deploy_prd.sh
├── handler.js
├── node_modules
│   ├── @babel
│   ├── JSONStream
│   ├── abab
│   ├── acorn
│   ├── acorn-dynamic-import
│   ├── acorn-globals
│   ├── acorn-node
│   ├── ajv
│   ├── align-text
│   ├── amdefine
│   ├── ansi-escapes
│   ├── ansi-regex
│   ├── ansi-styles
│   ├── anymatch
│   ├── append-transform
│   ├── argparse
│   ├── arr-diff
│   ├── arr-flatten
│   ├── arr-union
│   ├── array-equal
│   ├── array-filter
│   ├── array-map
│   ├── array-reduce
│   ├── array-unique
│   ├── arrify
│   ├── asn1
│   ├── asn1.js
│   ├── assert
│   ├── assert-plus
│   ├── assign-symbols
│   ├── astral-regex
│   ├── async
│   ├── async-limiter
│   ├── asynckit
│   ├── atob
│   ├── aws-sign2
│   ├── aws4
│   ├── babel-code-frame
│   ├── babel-core
│   ├── babel-generator
│   ├── babel-helper-builder-binary-assignment-operator-visitor
│   ├── babel-helper-call-delegate
│   ├── babel-helper-define-map
│   ├── babel-helper-evaluate-path
│   ├── babel-helper-explode-assignable-expression
│   ├── babel-helper-flip-expressions
│   ├── babel-helper-function-name
│   ├── babel-helper-get-function-arity
│   ├── babel-helper-hoist-variables
│   ├── babel-helper-is-nodes-equiv
│   ├── babel-helper-is-void-0
│   ├── babel-helper-mark-eval-scopes
│   ├── babel-helper-optimise-call-expression
│   ├── babel-helper-regex
│   ├── babel-helper-remap-async-to-generator
│   ├── babel-helper-remove-or-void
│   ├── babel-helper-replace-supers
│   ├── babel-helper-to-multiple-sequence-expressions
│   ├── babel-helpers
│   ├── babel-jest
│   ├── babel-messages
│   ├── babel-plugin-check-es2015-constants
│   ├── babel-plugin-istanbul
│   ├── babel-plugin-jest-hoist
│   ├── babel-plugin-minify-builtins
│   ├── babel-plugin-minify-constant-folding
│   ├── babel-plugin-minify-dead-code-elimination
│   ├── babel-plugin-minify-flip-comparisons
│   ├── babel-plugin-minify-guarded-expressions
│   ├── babel-plugin-minify-infinity
│   ├── babel-plugin-minify-mangle-names
│   ├── babel-plugin-minify-numeric-literals
│   ├── babel-plugin-minify-replace
│   ├── babel-plugin-minify-simplify
│   ├── babel-plugin-minify-type-constructors
│   ├── babel-plugin-syntax-async-functions
│   ├── babel-plugin-syntax-exponentiation-operator
│   ├── babel-plugin-syntax-object-rest-spread
│   ├── babel-plugin-syntax-trailing-function-commas
│   ├── babel-plugin-transform-async-to-generator
│   ├── babel-plugin-transform-es2015-arrow-functions
│   ├── babel-plugin-transform-es2015-block-scoped-functions
│   ├── babel-plugin-transform-es2015-block-scoping
│   ├── babel-plugin-transform-es2015-classes
│   ├── babel-plugin-transform-es2015-computed-properties
│   ├── babel-plugin-transform-es2015-destructuring
│   ├── babel-plugin-transform-es2015-duplicate-keys
│   ├── babel-plugin-transform-es2015-for-of
│   ├── babel-plugin-transform-es2015-function-name
│   ├── babel-plugin-transform-es2015-literals
│   ├── babel-plugin-transform-es2015-modules-amd
│   ├── babel-plugin-transform-es2015-modules-commonjs
│   ├── babel-plugin-transform-es2015-modules-systemjs
│   ├── babel-plugin-transform-es2015-modules-umd
│   ├── babel-plugin-transform-es2015-object-super
│   ├── babel-plugin-transform-es2015-parameters
│   ├── babel-plugin-transform-es2015-shorthand-properties
│   ├── babel-plugin-transform-es2015-spread
│   ├── babel-plugin-transform-es2015-sticky-regex
│   ├── babel-plugin-transform-es2015-template-literals
│   ├── babel-plugin-transform-es2015-typeof-symbol
│   ├── babel-plugin-transform-es2015-unicode-regex
│   ├── babel-plugin-transform-exponentiation-operator
│   ├── babel-plugin-transform-inline-consecutive-adds
│   ├── babel-plugin-transform-member-expression-literals
│   ├── babel-plugin-transform-merge-sibling-variables
│   ├── babel-plugin-transform-minify-booleans
│   ├── babel-plugin-transform-property-literals
│   ├── babel-plugin-transform-regenerator
│   ├── babel-plugin-transform-regexp-constructors
│   ├── babel-plugin-transform-remove-console
│   ├── babel-plugin-transform-remove-debugger
│   ├── babel-plugin-transform-remove-undefined
│   ├── babel-plugin-transform-simplify-comparison-operators
│   ├── babel-plugin-transform-strict-mode
│   ├── babel-plugin-transform-undefined-to-void
│   ├── babel-preset-env
│   ├── babel-preset-jest
│   ├── babel-preset-minify
│   ├── babel-register
│   ├── babel-runtime
│   ├── babel-template
│   ├── babel-traverse
│   ├── babel-types
│   ├── babelify
│   ├── babylon
│   ├── balanced-match
│   ├── base
│   ├── base64-js
│   ├── bcrypt-pbkdf
│   ├── bluebird
│   ├── bn.js
│   ├── brace-expansion
│   ├── braces
│   ├── brorand
│   ├── browser-pack
│   ├── browser-process-hrtime
│   ├── browser-resolve
│   ├── browserify
│   ├── browserify-aes
│   ├── browserify-cipher
│   ├── browserify-des
│   ├── browserify-rsa
│   ├── browserify-sign
│   ├── browserify-zlib
│   ├── browserslist
│   ├── bser
│   ├── bson
│   ├── buffer
│   ├── buffer-from
│   ├── buffer-xor
│   ├── builtin-modules
│   ├── builtin-status-codes
│   ├── cache-base
│   ├── cached-path-relative
│   ├── callsites
│   ├── camelcase
│   ├── caniuse-lite
│   ├── capture-exit
│   ├── caseless
│   ├── center-align
│   ├── chalk
│   ├── ci-info
│   ├── cipher-base
│   ├── class-utils
│   ├── cliui
│   ├── co
│   ├── code-point-at
│   ├── collection-visit
│   ├── color-convert
│   ├── color-name
│   ├── combine-source-map
│   ├── combined-stream
│   ├── compare-versions
│   ├── component-emitter
│   ├── concat-map
│   ├── concat-stream
│   ├── console-browserify
│   ├── constants-browserify
│   ├── convert-source-map
│   ├── copy-descriptor
│   ├── core-js
│   ├── core-util-is
│   ├── create-ecdh
│   ├── create-hash
│   ├── create-hmac
│   ├── cross-spawn
│   ├── crypto-browserify
│   ├── cssom
│   ├── cssstyle
│   ├── dashdash
│   ├── data-urls
│   ├── date-now
│   ├── debug
│   ├── decamelize
│   ├── decode-uri-component
│   ├── deep-is
│   ├── default-require-extensions
│   ├── define-properties
│   ├── define-property
│   ├── defined
│   ├── delayed-stream
│   ├── deps-sort
│   ├── des.js
│   ├── detect-indent
│   ├── detect-newline
│   ├── detective
│   ├── diff
│   ├── diffie-hellman
│   ├── domain-browser
│   ├── domexception
│   ├── duplexer2
│   ├── ecc-jsbn
│   ├── electron-to-chromium
│   ├── elliptic
│   ├── error-ex
│   ├── es-abstract
│   ├── es-to-primitive
│   ├── escape-string-regexp
│   ├── escodegen
│   ├── esprima
│   ├── estraverse
│   ├── esutils
│   ├── events
│   ├── evp_bytestokey
│   ├── exec-sh
│   ├── execa
│   ├── exit
│   ├── expand-brackets
│   ├── expand-range
│   ├── expect
│   ├── extend
│   ├── extend-shallow
│   ├── extglob
│   ├── extsprintf
│   ├── fast-deep-equal
│   ├── fast-json-stable-stringify
│   ├── fast-levenshtein
│   ├── fb-watchman
│   ├── filename-regex
│   ├── fileset
│   ├── fill-range
│   ├── find-up
│   ├── for-in
│   ├── for-own
│   ├── foreach
│   ├── forever-agent
│   ├── form-data
│   ├── fragment-cache
│   ├── fs-extra
│   ├── fs.realpath
│   ├── fsevents
│   ├── function-bind
│   ├── get-assigned-identifiers
│   ├── get-caller-file
│   ├── get-stream
│   ├── get-value
│   ├── getpass
│   ├── glob
│   ├── glob-base
│   ├── glob-parent
│   ├── globals
│   ├── graceful-fs
│   ├── growly
│   ├── handlebars
│   ├── har-schema
│   ├── har-validator
│   ├── has
│   ├── has-ansi
│   ├── has-flag
│   ├── has-value
│   ├── has-values
│   ├── hash-base
│   ├── hash.js
│   ├── hmac-drbg
│   ├── home-or-tmp
│   ├── hosted-git-info
│   ├── html-encoding-sniffer
│   ├── htmlescape
│   ├── http-signature
│   ├── https-browserify
│   ├── iconv-lite
│   ├── ieee754
│   ├── import-local
│   ├── imurmurhash
│   ├── inflight
│   ├── inherits
│   ├── inline-source-map
│   ├── insert-module-globals
│   ├── invariant
│   ├── invert-kv
│   ├── is-accessor-descriptor
│   ├── is-arrayish
│   ├── is-buffer
│   ├── is-builtin-module
│   ├── is-callable
│   ├── is-ci
│   ├── is-data-descriptor
│   ├── is-date-object
│   ├── is-descriptor
│   ├── is-dotfile
│   ├── is-equal-shallow
│   ├── is-extendable
│   ├── is-extglob
│   ├── is-finite
│   ├── is-fullwidth-code-point
│   ├── is-generator-fn
│   ├── is-glob
│   ├── is-number
│   ├── is-plain-object
│   ├── is-posix-bracket
│   ├── is-primitive
│   ├── is-regex
│   ├── is-stream
│   ├── is-symbol
│   ├── is-typedarray
│   ├── is-utf8
│   ├── is-windows
│   ├── isarray
│   ├── isexe
│   ├── isobject
│   ├── isstream
│   ├── istanbul-api
│   ├── istanbul-lib-coverage
│   ├── istanbul-lib-hook
│   ├── istanbul-lib-instrument
│   ├── istanbul-lib-report
│   ├── istanbul-lib-source-maps
│   ├── istanbul-reports
│   ├── jest
│   ├── jest-changed-files
│   ├── jest-config
│   ├── jest-diff
│   ├── jest-docblock
│   ├── jest-each
│   ├── jest-environment-jsdom
│   ├── jest-environment-node
│   ├── jest-get-type
│   ├── jest-haste-map
│   ├── jest-jasmine2
│   ├── jest-leak-detector
│   ├── jest-matcher-utils
│   ├── jest-message-util
│   ├── jest-mock
│   ├── jest-regex-util
│   ├── jest-resolve
│   ├── jest-resolve-dependencies
│   ├── jest-runner
│   ├── jest-runtime
│   ├── jest-serializer
│   ├── jest-snapshot
│   ├── jest-util
│   ├── jest-validate
│   ├── jest-watcher
│   ├── jest-worker
│   ├── js-tokens
│   ├── js-yaml
│   ├── jsbn
│   ├── jsdom
│   ├── jsesc
│   ├── json-schema
│   ├── json-schema-traverse
│   ├── json-stable-stringify
│   ├── json-stringify-safe
│   ├── json5
│   ├── jsonfile
│   ├── jsonify
│   ├── jsonparse
│   ├── jsprim
│   ├── kareem
│   ├── kind-of
│   ├── kleur
│   ├── labeled-stream-splicer
│   ├── lazy-cache
│   ├── lcid
│   ├── left-pad
│   ├── leven
│   ├── levn
│   ├── load-json-file
│   ├── locate-path
│   ├── lodash
│   ├── lodash.get
│   ├── lodash.isplainobject
│   ├── lodash.memoize
│   ├── lodash.some
│   ├── lodash.sortby
│   ├── longest
│   ├── loose-envify
│   ├── lru-cache
│   ├── makeerror
│   ├── map-cache
│   ├── map-visit
│   ├── math-random
│   ├── md5.js
│   ├── mem
│   ├── merge
│   ├── merge-stream
│   ├── micromatch
│   ├── miller-rabin
│   ├── mime-db
│   ├── mime-types
│   ├── mimic-fn
│   ├── minimalistic-assert
│   ├── minimalistic-crypto-utils
│   ├── minimatch
│   ├── minimist
│   ├── mixin-deep
│   ├── mkdirp
│   ├── mockingoose
│   ├── module-deps
│   ├── mongodb
│   ├── mongodb-core
│   ├── mongoose
│   ├── mongoose-legacy-pluralize
│   ├── mpath
│   ├── mquery
│   ├── ms
│   ├── nan
│   ├── nanomatch
│   ├── natural-compare
│   ├── node-int64
│   ├── node-notifier
│   ├── normalize-package-data
│   ├── normalize-path
│   ├── npm-run-path
│   ├── number-is-nan
│   ├── nwsapi
│   ├── oauth-sign
│   ├── object-assign
│   ├── object-copy
│   ├── object-keys
│   ├── object-visit
│   ├── object.getownpropertydescriptors
│   ├── object.omit
│   ├── object.pick
│   ├── once
│   ├── optimist
│   ├── optionator
│   ├── os-browserify
│   ├── os-homedir
│   ├── os-locale
│   ├── os-tmpdir
│   ├── p-finally
│   ├── p-limit
│   ├── p-locate
│   ├── p-try
│   ├── pako
│   ├── parents
│   ├── parse-asn1
│   ├── parse-glob
│   ├── parse-json
│   ├── parse5
│   ├── pascalcase
│   ├── path-browserify
│   ├── path-exists
│   ├── path-is-absolute
│   ├── path-key
│   ├── path-parse
│   ├── path-platform
│   ├── path-type
│   ├── pbkdf2
│   ├── performance-now
│   ├── pify
│   ├── pinkie
│   ├── pinkie-promise
│   ├── pkg-dir
│   ├── pn
│   ├── posix-character-classes
│   ├── prelude-ls
│   ├── preserve
│   ├── pretty-format
│   ├── private
│   ├── process
│   ├── process-nextick-args
│   ├── prompts
│   ├── pseudomap
│   ├── psl
│   ├── public-encrypt
│   ├── punycode
│   ├── qs
│   ├── querystring
│   ├── querystring-es3
│   ├── randomatic
│   ├── randombytes
│   ├── randomfill
│   ├── read-only-stream
│   ├── read-pkg
│   ├── read-pkg-up
│   ├── readable-stream
│   ├── realpath-native
│   ├── regenerate
│   ├── regenerator-runtime
│   ├── regenerator-transform
│   ├── regex-cache
│   ├── regex-not
│   ├── regexp-clone
│   ├── regexpu-core
│   ├── regjsgen
│   ├── regjsparser
│   ├── remove-trailing-separator
│   ├── repeat-element
│   ├── repeat-string
│   ├── repeating
│   ├── request
│   ├── request-promise-core
│   ├── request-promise-native
│   ├── require-directory
│   ├── require-main-filename
│   ├── require_optional
│   ├── resolve
│   ├── resolve-cwd
│   ├── resolve-from
│   ├── resolve-url
│   ├── ret
│   ├── right-align
│   ├── rimraf
│   ├── ripemd160
│   ├── rsvp
│   ├── safe-buffer
│   ├── safe-regex
│   ├── safer-buffer
│   ├── sane
│   ├── saslprep
│   ├── sax
│   ├── semver
│   ├── serverless-http
│   ├── serverless-plugin-optimize
│   ├── set-blocking
│   ├── set-value
│   ├── sha.js
│   ├── shasum
│   ├── shebang-command
│   ├── shebang-regex
│   ├── shell-quote
│   ├── shellwords
│   ├── signal-exit
│   ├── simple-concat
│   ├── sisteransi
│   ├── slash
│   ├── sliced
│   ├── snapdragon
│   ├── snapdragon-node
│   ├── snapdragon-util
│   ├── source-map
│   ├── source-map-resolve
│   ├── source-map-support
│   ├── source-map-url
│   ├── spdx-correct
│   ├── spdx-exceptions
│   ├── spdx-expression-parse
│   ├── spdx-license-ids
│   ├── split-string
│   ├── sprintf-js
│   ├── sshpk
│   ├── stack-utils
│   ├── static-extend
│   ├── stealthy-require
│   ├── stream-browserify
│   ├── stream-combiner2
│   ├── stream-http
│   ├── stream-splicer
│   ├── string-length
│   ├── string-width
│   ├── string_decoder
│   ├── strip-ansi
│   ├── strip-bom
│   ├── strip-eof
│   ├── subarg
│   ├── supports-color
│   ├── symbol-tree
│   ├── syntax-error
│   ├── test-exclude
│   ├── throat
│   ├── through
│   ├── through2
│   ├── timers-browserify
│   ├── tmpl
│   ├── to-arraybuffer
│   ├── to-fast-properties
│   ├── to-object-path
│   ├── to-regex
│   ├── to-regex-range
│   ├── tough-cookie
│   ├── tr46
│   ├── trim-right
│   ├── tty-browserify
│   ├── tunnel-agent
│   ├── tweetnacl
│   ├── type-check
│   ├── typedarray
│   ├── uglify-js
│   ├── uglify-to-browserify
│   ├── umd
│   ├── undeclared-identifiers
│   ├── union-value
│   ├── universalify
│   ├── unset-value
│   ├── urix
│   ├── url
│   ├── use
│   ├── util
│   ├── util-deprecate
│   ├── util.promisify
│   ├── uuid
│   ├── validate-npm-package-license
│   ├── verror
│   ├── vm-browserify
│   ├── w3c-hr-time
│   ├── walker
│   ├── watch
│   ├── webidl-conversions
│   ├── whatwg-encoding
│   ├── whatwg-mimetype
│   ├── whatwg-url
│   ├── which
│   ├── which-module
│   ├── window-size
│   ├── wordwrap
│   ├── wrap-ansi
│   ├── wrappy
│   ├── write-file-atomic
│   ├── ws
│   ├── xml-name-validator
│   ├── xtend
│   ├── y18n
│   ├── yallist
│   ├── yargs
│   └── yargs-parser
├── package-lock.json
├── package.json
├── serverless.yml
└── testsInt
    ├── apis
    ├── oEmbedTest.js
    └── utils
```

**Comment by Demven** [comment]
Have you found any solution? I'm having the same problem!

**Comment by anantkas-zerone** [comment]
@rodrigoreis22's wasn't enough is there anything else that needs to be done?

**Comment by rodrigoreis22** [comment]
@anantkas-zerone can you paste your serverless.yaml ?

**Comment by anantkas-zerone** [comment]
service: rest-api

custom:
  stage: ${opt:stage, self:provider.stage}
  secrets: ${file(secrets.yml):${self:custom.stage}}

provider:
  name: aws
  runtime: nodejs8.10 # set node.js runtime
  memorySize: 128 # set the maximum memory of the Lambdas in Megabytes
  timeout: 10 # the timeout is 10 seconds (default is 6 seconds)
  stage: dev # setting the env stage to dev, this will be visible in the routes
  region: ap-south-1
  stackName: abc-stack
  apiName: abc
  exclude:
    - secrets.yml

plugins:
  - serverless-offline
  - serverless-plugin-optimize

package:
  individually: true

functions:
  hello:
    handler: src/hello/app.handler

    events:
      - http:
          path: /
          method: get
          cors: true

 userCheckMobile:
    handler: src/user/mobileController.handler

    events:
      - http:
          path: /user/mobile/{mobile}
          method: get
          cors: true

**Comment by rodrigoreis22** [comment]
@anantkas-zerone you need to set the mongoose lib as external, see the example below:

Function level configuration:
```
admin-api:
    handler: handler_admin_api.handler
    timeout: 30
    optimize:
      external: ['mongoose']
    events:
      - http:
          path: admin/{proxy+}
          method: ANY
          private: true
```

Global configuration via `custom`:
```
custom:
  stage: "${opt:stage, self:provider.stage}"
  optimize:
    debug: false
    external: ['mongoose']
  presence-frequency-dev: 10
  presence-frequency-prd: 2
```

**Comment by anantkas-zerone** [comment]
still doesn't seems to be working 

> Unable to import module '_optimize/rest-api-dev-registerUserController/src/user/registerController': Error
at Function.Module._resolveFilename (module.js:547:15)
at Function.Module._load (module.js:474:25)
at Module.require (module.js:596:17)
at require (internal/module.js:11:18)
at Object.<anonymous> (/var/task/_optimize/rest-api-dev-registerUserController/src/user/node_modules/mongoose/lib/drivers/node-mongodb-native/binary.js:8:16)
at Module._compile (module.js:652:30)
at Object.Module._extensions..js (module.js:663:10)
at Module.load (module.js:565:32)
at tryModuleLoad (module.js:505:12)
at Function.Module._load (module.js:497:3)

**Comment by anantkas-zerone** [comment]
tried 

cd node_modules/mongodb && npm i --production


 optimize:
      external: ["mongoose", "mongodb"]

to resolve the error but the optimized file shot to 22MB of size.

It showed different error 

> Unable to import module '_optimize/rest-api-dev-userCheckMobile/src/user/mobileController': Error
at Function.Module._resolveFilename (module.js:547:15)
at Function.Module._load (module.js:474:25)
at Module.require (module.js:596:17)
at require (internal/module.js:11:18)
at Object.<anonymous> (/var/task/_optimize/rest-api-dev-userCheckMobile/src/user/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:10:16)
a

I guess  the only way is to manual install and add all the files required by mongoose

**Comment by rodrigoreis22** [comment]
That's odd. Which version of mongoose are you using? I'm using `5.2.5` .

**Comment by rodrigoreis22** [comment]
Also @anantkas-zerone you have to explicitly import mongoose on your handler function as a global variable. I do this by calling a module I created:

db_init.js:
```
const mongoose = require('mongoose')
  , config = require('./config');

let conn = null;

module.exports = () => {
  const mongoDbConnString = config.mongoDbUri;

  if (conn && conn.readyState) {
    console.log('MongoDB is already connected = readyState = %s', conn.readyState);
    return;
  }

  console.log('Connecting to MongoDB: %s', mongoDbConnString);
  const options = {
    dbName: config.mongoDbName
  };
  mongoose.connect(mongoDbConnString, options);
  conn = mongoose.connection;
  conn.on('error', err => {
    console.log(err);
  });
  conn.once('open', () => {
    console.log('Connected to mongodb!');
  });
};
```


handler_billing_api.js:
```
'use strict';
const billing = require('./app/routes/billing');
const db = require('./app/db_init');
const config = require('./app/config');
const iopipe = require('@iopipe/iopipe')({ token: config.iopipeToken });

db();

module.exports.handler = iopipe((event, context, callback) => {
  context.iopipe.label(event.path);
  context.callbackWaitsForEmptyEventLoop = false;
  billing.run(event, context, callback);
});
```

**Comment by anantkas-zerone** [comment]
@rodrigoreis22 

> That's odd. Which version of mongoose are you using? I'm using `5.2.5` .

@rodrigoreis22 I am using 5.4.7

And 

> Also @anantkas-zerone you have to explicitly import mongoose on your handler function as a global variable. I do this by calling a module I created:
> 
> db_init.js:
> 
> ```
> const mongoose = require('mongoose')
>   , config = require('./config');
> 
> let conn = null;
> 
> module.exports = () => {
>   const mongoDbConnString = config.mongoDbUri;
> 
>   if (conn && conn.readyState) {
>     console.log('MongoDB is already connected = readyState = %s', conn.readyState);
>     return;
>   }
> 
>   console.log('Connecting to MongoDB: %s', mongoDbConnString);
>   const options = {
>     dbName: config.mongoDbName
>   };
>   mongoose.connect(mongoDbConnString, options);
>   conn = mongoose.connection;
>   conn.on('error', err => {
>     console.log(err);
>   });
>   conn.once('open', () => {
>     console.log('Connected to mongodb!');
>   });
> };
> ```
> handler_billing_api.js:
> 
> ```
> 'use strict';
> const billing = require('./app/routes/billing');
> const db = require('./app/db_init');
> const config = require('./app/config');
> const iopipe = require('@iopipe/iopipe')({ token: config.iopipeToken });
> 
> db();
> 
> module.exports.handler = iopipe((event, context, callback) => {
>   context.iopipe.label(event.path);
>   context.callbackWaitsForEmptyEventLoop = false;
>   billing.run(event, context, callback);
> });
> ```

I am doing the same rather than calling db_init in the handler function I have a service module for my users table where I first call the await my init method and then call rest of the model functions.

**Comment by rodrigoreis22** [comment]
@anantkas-zerone it might be a problem with this specific mongoose version. Try using `5.2.5`

**Comment by anantkas-zerone** [comment]
@rodrigoreis22 yes it is working with mongoose 5.2.5. Thanks.

**Comment by rodrigoreis22** [comment]
great @anantkas-zerone , I'm locked with this version.. in the future I will try to upgrade.

**Comment by michaelbats** [comment]
I'm getting this error with the latest version as well, I've downgraded to 5.2.5 and it's not working using optimize ``` 4.1.0-rc.1 ```

I can exclude mongoose and add it as a layer but still getting some random error with some node module that's completely irrelevant.

**Comment by imthatcarlos** [comment]
@michaelbats +1 I'm seeing the same error

**Comment by marcelobbfonseca** [comment]
Still no updates for newer versions?
