### ISSUE TITLE
Unable to import module

### ISSUE THREAD

**Issue by kvarela** [FidelLimited/serverless-plugin-optimize#63]
This worked at one point, but now I'm getting this while running in Lambda:

```Unable to import module '_optimize/graphql-api-dev-graphql/src/handlers/graphql': Error
at Function.Module._load (module.js:417:25)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at o (/var/task/_optimize/graphql-api-dev-graphql/src/handlers/graphql.js:1:554)
at /var/task/_optimize/graphql-api-dev-graphql/src/handlers/graphql.js:1:745
at Object.25.. (/var/task/_optimize/graphql-api-dev-graphql/src/handlers/graphql.js:76:851)
at o (/var/task/_optimize/graphql-api-dev-graphql/src/handlers/graphql.js:1:694)
at /var/task/_optimize/graphql-api-dev-graphql/src/handlers/graphql.js:1:745
at Object.33../AmenityService (/var/task/_optimize/graphql-api-dev-graphql/src/handlers/graphql.js:100:191)
```

Here's line 100 of my function:
```
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});var AmenityService_1=require("./AmenityService");exports.AmenityService=AmenityService_1.AmenityService;var AuthService_1=require("./AuthService");exports.AuthService=AuthService_1.AuthService;var HotelService_1=require("./HotelService");exports.HotelService=HotelService_1.HotelService;var LocationService_1=require("./LocationService");exports.LocationService=LocationService_1.LocationService;var EmailService_1=require("./EmailService");exports.EmailService=EmailService_1.EmailService;var FbService_1=require("./FbService");exports.FbService=FbService_1.FbService;var PolicyService_1=require("./PolicyService");exports.PolicyService=PolicyService_1.PolicyService;var Services_1=require("./Services");exports.Services=Services_1.Services;var UserService_1=require("./UserService");exports.UserService=UserService_1.UserService;
```

Any ideas?

**Comment by goncaloneves** [comment]
Jesus, you got into some issue warzone. 

What version of Serverless are you on mate and show me again your serverless.yml?

**Comment by kvarela** [comment]
Thanks for your replies. I've since got browserifier to work and am no
longer tinkering with optimize.

>
