### ISSUE TITLE
Unexpected Token while parsing file (spread operator)

### ISSUE THREAD

**Issue by gage-langdon** [FidelLimited/serverless-plugin-optimize#67]
I have tried to disable minification as i read as a solution from another issues here, but it still didnt work. 

Unexpected token (273:46) while parsing file at Parser.pp$5.raise

**Comment by daniele-pelagatti** [comment]
confirming this , on a snipplet like this

```javascript
    const Item = {
      id,
      _contentType: contentModel.id,
      _createdAt: new Date().toISOString(),
      _modifiedAt: new Date().toISOString(),
      ...args.input
    }
```

I get this error

```
SyntaxError: D:/Users/x/Desktop/proj/serverless/lambda-functions/content/index.js: Unexpected token (264:6) while parsing file: D:\Users\x\Desktop\proj\serverless\lambda-functions\content\index.js
SyntaxError: D:/Users/x/Desktop/proj/serverless/lambda-functions/content/index.js: Unexpected token (264:6)
  262 |       _createdAt: new Date().toISOString(),
  263 |       _modifiedAt: new Date().toISOString(),
> 264 |       ...args.input
      |       ^
  265 |     }
    at Parser.pp$5.raise (D:\Users\x\Desktop\proj\serverless\node_modules\babylon\lib\index.js:4454:13)
    at Parser.pp.unexpected (D:\Users\x\Desktop\proj\serverless\node_modules\babylon\lib\index.js:1761:8)
    at Parser.pp$3.parseIdentifier (D:\Users\x\Desktop\proj\serverless\node_modules\babylon\lib\index.js:4332:10)
    at Parser.pp$3.parsePropertyName (D:\Users\x\Desktop\proj\serverless\node_modules\babylon\lib\index.js:4156:96)
    at Parser.pp$3.parseObj (D:\Users\x\Desktop\proj\serverless\node_modules\babylon\lib\index.js:4045:12)
    at Parser.pp$3.parseExprAtom (D:\Users\x\Desktop\proj\serverless\node_modules\babylon\lib\index.js:3719:19)
    at Parser.pp$3.parseExprSubscripts (D:\Users\x\Desktop\proj\serverless\node_modules\babylon\lib\index.js:3494:19)
    at Parser.pp$3.parseMaybeUnary (D:\Users\x\Desktop\proj\serverless\node_modules\babylon\lib\index.js:3474:19)
    at Parser.pp$3.parseExprOps (D:\Users\x\Desktop\proj\serverless\node_modules\babylon\lib\index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (D:\Users\x\Desktop\proj\serverless\node_modules\babylon\lib\index.js:3381:19)
    at Parser.pp$3.parseMaybeAssign (D:\Users\x\Desktop\proj\serverless\node_modules\babylon\lib\index.js:3344:19)
    at Parser.pp$1.parseVar (D:\Users\x\Desktop\proj\serverless\node_modules\babylon\lib\index.js:2340:24)
    at Parser.pp$1.parseVarStatement (D:\Users\x\Desktop\proj\serverless\node_modules\babylon\lib\index.js:2169:8)
    at Parser.pp$1.parseStatement (D:\Users\x\Desktop\proj\serverless\node_modules\babylon\lib\index.js:1861:19)
    at Parser.pp$1.parseBlockBody (D:\Users\x\Desktop\proj\serverless\node_modules\babylon\lib\index.js:2268:21)
    at Parser.pp$1.parseBlock (D:\Users\x\Desktop\proj\serverless\node_modules\babylon\lib\index.js:2247:8)
    at Parser.pp$3.parseFunctionBody (D:\Users\x\Desktop\proj\serverless\node_modules\babylon\lib\index.js:4235:22)
    at Parser.pp$3.parseArrowExpression (D:\Users\x\Desktop\proj\serverless\node_modules\babylon\lib\index.js:4190:8)
    at Parser.pp$3.parseAsyncArrowFromCallExpression (D:\Users\x\Desktop\proj\serverless\node_modules\babylon\lib\index.js:3590:15)
    at Parser.pp$3.parseSubscripts (D:\Users\x\Desktop\proj\serverless\node_modules\babylon\lib\index.js:3540:21)
    at Parser.pp$3.parseExprSubscripts (D:\Users\x\Desktop\proj\serverless\node_modules\babylon\lib\index.js:3504:15)
    at Parser.pp$3.parseMaybeUnary (D:\Users\x\Desktop\proj\serverless\node_modules\babylon\lib\index.js:3474:19)
    at Parser.pp$3.parseExprOps (D:\Users\x\Desktop\proj\serverless\node_modules\babylon\lib\index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (D:\Users\x\Desktop\proj\serverless\node_modules\babylon\lib\index.js:3381:19)
    at Parser.pp$3.parseMaybeAssign (D:\Users\x\Desktop\proj\serverless\node_modules\babylon\lib\index.js:3344:19)
    at Parser.pp$3.parseMaybeAssign (D:\Users\x\Desktop\proj\serverless\node_modules\babylon\lib\index.js:3367:23)
    at Parser.pp$3.parseExpression (D:\Users\x\Desktop\proj\serverless\node_modules\babylon\lib\index.js:3306:19)
    at Parser.pp$1.parseStatement (D:\Users\x\Desktop\proj\serverless\node_modules\babylon\lib\index.js:1906:19)
    at Parser.pp$1.parseBlockBody (D:\Users\x\Desktop\proj\serverless\node_modules\babylon\lib\index.js:2268:21)
    at Parser.pp$1.parseBlock (D:\Users\x\Desktop\proj\serverless\node_modules\babylon\lib\index.js:2247:8)
    at Parser.pp$3.parseFunctionBody (D:\Users\x\Desktop\proj\serverless\node_modules\babylon\lib\index.js:4235:22)
    at Parser.pp$3.parseArrowExpression (D:\Users\x\Desktop\proj\serverless\node_modules\babylon\lib\index.js:4190:8)
    at Parser.pp$3.parseParenAndDistinguishExpression (D:\Users\x\Desktop\proj\serverless\node_modules\babylon\lib\index.js:3855:17)
    at Parser.pp$3.parseExprAtom (D:\Users\x\Desktop\proj\serverless\node_modules\babylon\lib\index.js:3709:19)
    at Parser.pp$3.parseExprSubscripts (D:\Users\x\Desktop\proj\serverless\node_modules\babylon\lib\index.js:3494:19)
    at Parser.pp$3.parseMaybeUnary (D:\Users\x\Desktop\proj\serverless\node_modules\babylon\lib\index.js:3474:19)
    at Parser.pp$3.parseExprOps (D:\Users\x\Desktop\proj\serverless\node_modules\babylon\lib\index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (D:\Users\x\Desktop\proj\serverless\node_modules\babylon\lib\index.js:3381:19)
    at Parser.pp$3.parseMaybeAssign (D:\Users\x\Desktop\proj\serverless\node_modules\babylon\lib\index.js:3344:19)
    at Parser.pp$1.parseVar (D:\Users\x\Desktop\proj\serverless\node_modules\babylon\lib\index.js:2340:24)
    at Parser.pp$1.parseVarStatement (D:\Users\x\Desktop\proj\serverless\node_modules\babylon\lib\index.js:2169:8)
    at Parser.pp$1.parseStatement (D:\Users\x\Desktop\proj\serverless\node_modules\babylon\lib\index.js:1861:19)
    at Parser.pp$1.parseBlockBody (D:\Users\x\Desktop\proj\serverless\node_modules\babylon\lib\index.js:2268:21)
    at Parser.pp$1.parseTopLevel (D:\Users\x\Desktop\proj\serverless\node_modules\babylon\lib\index.js:1778:8)
    at Parser.parse (D:\Users\x\Desktop\proj\serverless\node_modules\babylon\lib\index.js:1673:17)
    at parse (D:\Users\x\Desktop\proj\serverless\node_modules\babylon\lib\index.js:7305:37)
    at File.parse (D:\Users\x\Desktop\proj\serverless\node_modules\babel-core\lib\transformation\file\index.js:485:15)
    at File.parseCode (D:\Users\x\Desktop\proj\serverless\node_modules\babel-core\lib\transformation\file\index.js:570:20)
    at D:\Users\x\Desktop\proj\serverless\node_modules\babel-core\lib\transformation\pipeline.js:49:12
    at File.wrap (D:\Users\x\Desktop\proj\serverless\node_modules\babel-core\lib\transformation\file\index.js:532:16)
    at Pipeline.transform (D:\Users\x\Desktop\proj\serverless\node_modules\babel-core\lib\transformation\pipeline.js:47:17)
    at Babelify._flush (D:\Users\x\Desktop\proj\serverless\node_modules\babelify\index.js:26:24)
    at Babelify.prefinish (_stream_transform.js:141:10)
    at Babelify.emit (events.js:182:13)
    at Babelify.EventEmitter.emit (domain.js:442:20)
    at prefinish (_stream_writable.js:630:14)
    at finishMaybe (_stream_writable.js:638:5)
    at endWritable (_stream_writable.js:649:3)
    at Babelify.Writable.end (_stream_writable.js:589:5)
    at DuplexWrapper.<anonymous> (D:\Users\x\Desktop\proj\serverless\node_modules\duplexer2\index.js:29:14)
    at Object.onceWrapper (events.js:273:13)
    at DuplexWrapper.emit (events.js:187:15)
    at DuplexWrapper.EventEmitter.emit (domain.js:442:20)
    at finishMaybe (D:\Users\x\Desktop\proj\serverless\node_modules\readable-stream\lib\_stream_writable.js:630:14)
    at endWritable (D:\Users\x\Desktop\proj\serverless\node_modules\readable-stream\lib\_stream_writable.js:638:3)
    at DuplexWrapper.Writable.end (D:\Users\x\Desktop\proj\serverless\node_modules\readable-stream\lib\_stream_writable.js:594:41)
    at DestroyableTransform.onend (D:\Users\x\Desktop\proj\serverless\node_modules\readable-stream\lib\_stream_readable.js:577:10)
    at Object.onceWrapper (events.js:273:13)
    at DestroyableTransform.emit (events.js:187:15)
    at DestroyableTransform.EventEmitter.emit (domain.js:442:20)
    at endReadableNT (D:\Users\x\Desktop\proj\serverless\node_modules\readable-stream\lib\_stream_readable.js:1010:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
From previous event:
    at PluginManager.invoke (C:\Users\x\AppData\Local\Yarn\Data\global\node_modules\serverless\lib\classes\PluginManager.js:390:22)
    at PluginManager.run (C:\Users\x\AppData\Local\Yarn\Data\global\node_modules\serverless\lib\classes\PluginManager.js:421:17)
    at variables.populateService.then.then (C:\Users\x\AppData\Local\Yarn\Data\global\node_modules\serverless\lib\Serverless.js:157:33)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
    at process.topLevelDomainCallback (domain.js:121:23)
From previous event:
    at Serverless.run (C:\Users\x\AppData\Local\Yarn\Data\global\node_modules\serverless\lib\Serverless.js:144:8)
    at serverless.init.then (C:\Users\x\AppData\Local\Yarn\Data\global\node_modules\serverless\bin\serverless:43:50)
```

**Comment by loweoj** [comment]
This is likely an issue with bowserify, no? See https://github.com/browserify/browserify/issues/1802

**Comment by goncaloneves** [comment]
Yes, Browserify doesn't support all new fancy syntax/statements. Please refer to Browserify docs.

**Comment by goncaloneves** [comment]
For the sake of curiosity, what babel preset were you using?
