### ISSUE TITLE
"Error: Cannot find module './drivers/node-mongodb-native/connection'" when used with optimize

### ISSUE THREAD

**Issue by michaelbats** [FidelLimited/serverless-plugin-optimize#85]
[Stackoverflow thread here.](https://stackoverflow.com/questions/57726007/lambda-cannot-find-module-drivers-node-mongodb-native-connection-although)

I've also added mongoose as a separate layer with all of its dependencies, it throws the exact same error. Is there something special I have to config somewhere to get this to work?

On the list of third-party modules this is supposed to work with, mongoose must be quite high as it is the most popular choice for mongodb via node.

**Comment by michaelbats** [comment]
I've just bundled my app with the `serverless-plugin-monorepo` and it works, but my bundle is 40mb instead of 2 so that's not cool. If I exclude 'mongoose' using the custom -> optimizer -> exclude: ['mongoose'] I don't get that error but I do get the following error:
```
    "errorType": "Error",
    "errorMessage": "ENOENT: no such file or directory, scandir '/var/task/_optimize/tlabs-api-dev-main/src/node_modules/pkginfo'",
    "code": "ENOENT",
    "stack": [
        "Error: ENOENT: no such file or directory, scandir '/var/task/_optimize/tlabs-api-dev-main/src/node_modules/pkginfo'",
        "    at Object.readdirSync (fs.js:790:3)",
        "    at Function.pkginfo.find (/var/task/_optimize/tlabs-api-dev-main/src/lambda.js:112662:18)",
        "    at Function.pkginfo.read (/var/task/_optimize/tlabs-api-dev-main/src/lambda.js:112686:17)",
        "    at module.exports (/var/task/_optimize/tlabs-api-dev-main/src/lambda.js:112637:21)",
        "    at Object.<anonymous> (/var/task/_optimize/tlabs-api-dev-main/src/lambda.js:112699:1)",
        "    at Object.789.fs (/var/task/_optimize/tlabs-api-dev-main/src/lambda.js:112704:4)",
        "    at o (/var/task/_optimize/tlabs-api-dev-main/src/lambda.js:1:632)",
        "    at /var/task/_optimize/tlabs-api-dev-main/src/lambda.js:1:683",
        "    at Object.758../strategy (/var/task/_optimize/tlabs-api-dev-main/src/lambda.js:109729:1)",
        "    at o (/var/task/_optimize/tlabs-api-dev-main/src/lambda.js:1:632)",
        "    at /var/task/_optimize/tlabs-api-dev-main/src/lambda.js:1:683",
        "    at Object.6.@nestjs/common (/var/task/_optimize/tlabs-api-dev-main/src/lambda.js:17:1182)",
        "    at o (/var/task/_optimize/tlabs-api-dev-main/src/lambda.js:1:632)",
        "    at /var/task/_optimize/tlabs-api-dev-main/src/lambda.js:1:683",
        "    at Object.5../google.strategy (/var/task/_optimize/tlabs-api-dev-main/src/lambda.js:14:565)",
        "    at o (/var/task/_optimize/tlabs-api-dev-main/src/lambda.js:1:632)"
    ],
    "errno": -2,
    "syscall": "scandir",
    "path": "/var/task/_optimize/tlabs-api-dev-main/src/node_modules/pkginfo"
``` 

Am i correct to assume that package is not being bundled correctly with the whole thing? I couldn't find any reason why that dependency is even there though.

**Comment by michaelbats** [comment]
Managed to exclude mongoose successfully. The second error was for a crappy dependency of another package, I changed that package with something else that doesn't have those dependencies, now getting: 
```
 "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module './stores/memory'",
```
Is this really optimizing anything at all if I have to manually remove a bunch of dependencies that break the whole thing?

**Comment by maazmk** [comment]
any update on this?

**Comment by sebastiangug** [comment]
Yeah, the update is to stop using serverless for deploying any kind of serious infrastructure

**Comment by dhiraj-indusved** [comment]
Anyone coming here for `Error: Cannot find module './drivers/node-mongodb-native/connection`

I found a solution here https://github.com/Automattic/mongoose/issues/9603 , thanks to hugdru

The problem is some parts of `mongoose` are required dynamically using a variable. One can use https://www.npmjs.com/package/patch-package to create a temporary patch until the next major release of mongoose where this is going to be fixed.

Changes to be made in `node_modules/mongoose/lib/index.js` with the changes given here https://gist.github.com/hugdru/982a31d929a030e29f852c4bfafd9b16 and the. just run `yarn patch-package mongoose`
