### ISSUE TITLE
Missing dependencies in bundle

### ISSUE THREAD

**Issue by davidfells** [FidelLimited/serverless-plugin-optimize#98]
I have a function with the following:

const puppeteerCore = require('puppeteer-core');
const chromium = require('chrome-aws-lambda');

Once deployed, there are errors from inside the chrome-aws-lambda package when it tries to include files from subfolders in it's npm_modules. I've tried various includePaths values, but I can't seem to get it to actually bundle everything for this function to work. Other required modules such as async, axios, and cheerio work fine. 

The specific error is below:

INFO	Error: Cannot find module '/var/task/_optimize/pricr-development-pricingFetch/functions/node_modules/chrome-aws-lambda/source/puppeteer/lib/FrameManager'
Require stack:
- /var/task/_optimize/pricr-development-pricingFetch/functions/pricing/fetch/function.js
- /var/task/s_pricingFetch.js
- /var/runtime/UserFunction.js
- /var/runtime/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Module._require.o.require (/var/task/serverless_sdk/index.js:9:72748)
    at require (internal/modules/cjs/helpers.js:77:18)
    at o (/var/task/_optimize/pricr-development-pricingFetch/functions/pricing/fetch/function.js:1:492)
    at /var/task/_optimize/pricr-development-pricingFetch/functions/pricing/fetch/function.js:1:683
    at Function.get puppeteer [as puppeteer] (/var/task/_optimize/pricr-development-pricingFetch/functions/pricing/fetch/function.js:13769:7)
    at module.exports.handler (/var/task/_optimize/pricr-development-pricingFetch/functions/pricing/fetch/function.js:58509:351)
    at Runtime.handler (/var/task/serverless_sdk/index.js:9:137042)
    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/task/_optimize/pricr-development-pricingFetch/functions/pricing/fetch/function.js',
    '/var/task/s_pricingFetch.js',
    '/var/runtime/UserFunction.js',
    '/var/runtime/index.js'
  ]
}

**Comment by davidfells** [comment]
This was a Webpack issue
